apiVersion: v1
kind: Service
metadata:
  name: term-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector: {}
