apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: term-server-

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: term-server

resources:
- backend/
- frontend/
